---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2023 The Nephio Authors.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- name: Upgrade Nephio packages
  ansible.builtin.include_tasks: update.yml
  loop: "{{ nephio.kpt.packages }}"
  vars:
    pkg_path: "{{ workdir }}"
    pkg: "{{ item.pkg }}"
    version: "{{ item.version }}"
    context: "{{ k8s.context }}"
    kpt_async: "{{ item.async }}"
    kpt_poll: "{{ item.poll }}"

- name: Wait for packages to be updated
  ansible.builtin.async_status:
    jid: "{{ item.ansible_job_id }}"
  register: job_result
  loop: "{{ all_kpt_update }}"
  when: all_kpt_update is defined
  until: job_result.finished
  retries: 60
  delay: 5

- name: Wait for deployments
  ansible.builtin.include_tasks: wait_deployments.yml
  loop: "{{ nephio.k8s.namespaces }}"
  loop_control:
    loop_var: namespace
  vars:
    context: "{{ k8s.context }}"
