---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2023 The Nephio Authors.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- name: Get deployment resources
  become: true
  kubernetes.core.k8s_info:
    context: "{{ context }}"
    api_version: v1
    kind: Deployment
    namespace: "{{ namespace }}"
  register: deployment_list

- name: Print deployment resources
  ansible.builtin.debug:
    var: deployment_list.resources

- name: Wait for deployments
  become: true
  kubernetes.core.k8s:
    context: "{{ context }}"
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: "{{ resource.metadata.name }}"
        namespace: "{{ resource.metadata.namespace }}"
    wait: true
    wait_condition:
      type: Available
      reason: MinimumReplicasAvailable
  loop: "{{ deployment_list.resources }}"
  loop_control:
    loop_var: resource
