---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2023 The Nephio Authors.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- name: Converge
  hosts: all
  tasks:
    - name: Set Gitea config
      ansible.builtin.set_fact:
        k8s:
          context: kind-kind
        gitea:
          k8s:
            namespace: gitea
            username: nephio
            password: secret

    - name: Set local git facts
      ansible.builtin.include_tasks: ../../../bootstrap/tasks/post-gitea.yml

    - name: Include install
      ansible.builtin.include_role:
        name: install
