---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2023 The Nephio Authors.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

dependency:
  name: galaxy
  options:
    role-file: ../../../galaxy-requirements.yml
driver:
  name: vagrant
lint: |
  set -e
  PATH=${PATH}
  yamllint -c ../../../.yaml-lint.yml .
  ansible-lint -v -c ../../../.ansible-lint
  flake8
platforms:
  - name: focal
    box: generic/ubuntu2004
    provider_options:
      gui: false
  - name: jammy
    box: generic/ubuntu2204
    provider_options:
      gui: false
provisioner:
  name: ansible
  playbooks:
    prepare: ${MOLECULE_PROJECT_DIRECTORY}/../kpt/molecule/default/prepare.yml
  env:
    ANSIBLE_LIBRARY: ${MOLECULE_PROJECT_DIRECTORY}/../../../playbooks/library
verifier:
  name: testinfra
  options:
    sudo: true
