---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2023 The Nephio Authors.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################


- name: Define working directory
  ansible.builtin.set_fact:
    workdir: "/tmp/{{ item }}"

- name: "Fetch kpt package: {{ item }}"
  kpt:
    command: pkg-get
    repo_uri: "{{ nephio_example_repo_uri }}"
    pkg_path: "{{ item }}"
    version: "{{ nephio_pkg_version }}"
    local_dest_directory: "{{ workdir }}"
    for_deployment: true

- name: "Render kpt package: {{ item }}"
  kpt:
    command: fn-render
    pkg_path: "{{ workdir }}"

- name: "Init kpt package: {{ item }}"
  kpt:
    command: live-init
    pkg_path: "{{ workdir }}"
    context: "{{ k8s.context }}"

- name: "Apply kpt package: {{ item }}"
  kpt:
    command: live-apply
    pkg_path: "{{ workdir }}"
    context: "{{ context }}"
    reconcile_timeout: "15m"
  changed_when: false
  register: kpt_apply_result
  until: kpt_apply_result is not failed
  retries: 5
  delay: 10

