---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2023 The Nephio Authors.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- name: "Fetch kpt package: {{ item }}"
  ansible.builtin.command:
    cmd: "kpt pkg get --for-deployment '{{ nephio_example_repo_uri }}/{{ item }}@{{ nephio_pkg_version }}'"
    chdir: "/tmp"
  changed_when: false

- name: "Render kpt package: {{ item }}"
  ansible.builtin.command:
    cmd: "kpt fn render"
    chdir: "/tmp/{{ item }}"
  changed_when: false

- name: "Init kpt package: {{ item }}"
  ansible.builtin.command:
    cmd: "kpt live init --namespace default --context {{ k8s.context }}"
    chdir: "/tmp/{{ item }}"
  changed_when: false

- name: "Apply kpt package: {{ item }}"
  ansible.builtin.command:
    cmd: "kpt live apply --namespace default --reconcile-timeout 15m --context {{ k8s.context }}"
    chdir: "/tmp/{{ item }}"
  changed_when: false
